# argocd/nginx-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-application
  namespace: argocd # ArgoCD Application resources are typically deployed in the argocd namespace
spec:
  project: default # Use the default ArgoCD project

  source:
    repoURL: https://github.com/GiteshWork/devops-eks-cicd.git 
    targetRevision: HEAD # Sync from the latest commit on the main/master branch
    path: manifests # The path WITHIN YOUR GIT REPOSITORY where NGINX manifests are located

  destination:
    server: https://kubernetes.default.svc # This refers to the EKS cluster's internal Kubernetes API server
    namespace: default # The namespace IN EKS where NGINX will be deployed

  syncPolicy:
    automated:
      prune: true # Delete Kubernetes resources that are no longer in Git
      selfHeal: true # Automatically sync if there's a drift from Git state
    syncOptions:
      - CreateNamespace=true # Optional: Create the target namespace if it doesn't exist
